version: "3.8"
services:
  app:
    container_name: rentsolute-app
    user: "1000:1000"
    networks:
      - rentsolute
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    image: new/phpfpm
    volumes:
      - .:/var/www/html
      - ./docker/app/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    working_dir: /var/www/html
    environment:
      - XDG_CONFIG_HOME=./

  queue:
    container_name: rentsolute-queue
    user: "1000:1000"
    networks:
      - rentsolute
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    image: new/phpfpm
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./docker/app/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    command: bash -c "php artisan queue:work"
    working_dir: /var/www/html
    environment:
      - XDG_CONFIG_HOME=./

  composer:
    container_name: rentsolute-composer
    user: "1000:1000"
    networks:
      - rentsolute
    build:
      context: ./docker/composer/
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: bash -c "composer install"

  node:
    container_name: rentsolute-node
    user: "1000:1000"
    ports:
      - 13714:13714
    networks:
      - rentsolute
    image: node:18
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: bash -c "npm cache clear --force && npm install && npm run watch"

  web:
    container_name: rentsolute-web
    image: httpd:2.4
    networks:
      - rentsolute
      - traefik-public
    volumes:
      - .:/var/www/html
      - ./docker/apache/vhost.conf:/usr/local/apache2/conf/vhost.conf
      - ./docker/apache/apache.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/apache/logs:/var/apache_logs
    labels:
        # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.rentsolute.rule=Host(`${DOMAIN:-rentsolute.localhost}`)
      - traefik.http.routers.rentsolute.entrypoints=${PROTOCOL:-http}
      - "traefik.http.routers.rentsolute.service=rentsolute-service"
      - "traefik.http.services.rentsolute-service.loadbalancer.server.port=80"

  db:
    container_name: rentsolute-db
    image: mysql:5.7
    platform: linux/x86_64
    networks:
      - rentsolute
      - traefik-public
    environment:
      MYSQL_DATABASE: ecommerce_indian
      MYSQL_USER: laravel_root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql


networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
  rentsolute:
    name: 'rentsolute'
